//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMobile.Server.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMobile.Server.Language.ErrorResources", typeof(ErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业务文件不存在，请检查！.
        /// </summary>
        public static string SYSTEM_COMM_ERROR_0x0001 {
            get {
                return ResourceManager.GetString("SYSTEM_COMM_ERROR_0x0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无权限访问！.
        /// </summary>
        public static string SYSTEM_COMM_ERROR_0x0002 {
            get {
                return ResourceManager.GetString("SYSTEM_COMM_ERROR_0x0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会话状态不正确！.
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x0001 {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x0002 {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x0003 {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x0004 {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x0005 {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x0006 {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x0007 {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x0008 {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x0009 {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x000B {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x000B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x000C {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x000C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x000D {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x000D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x000E {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x000E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x000F {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x000F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_FATAL_ERROR_0x00A {
            get {
                return ResourceManager.GetString("SYSTEM_FATAL_ERROR_0x00A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有结果..
        /// </summary>
        public static string SYSTEM_INFO_0x0001 {
            get {
                return ResourceManager.GetString("SYSTEM_INFO_0x0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SYSTEM_INFO_0x0002 {
            get {
                return ResourceManager.GetString("SYSTEM_INFO_0x0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求数据为空！.
        /// </summary>
        public static string SYSTEM_WARNING_0x0001 {
            get {
                return ResourceManager.GetString("SYSTEM_WARNING_0x0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求数据无法解析！.
        /// </summary>
        public static string SYSTEM_WARNING_0x0002 {
            get {
                return ResourceManager.GetString("SYSTEM_WARNING_0x0002", resourceCulture);
            }
        }
    }
}
